# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    enp6s0:
      dhcp4: false
      dhcp6: false

  bridges:
    br0:
      interfaces: [enp6s0]
#      addresses: [192.168.1.20/24]
      dhcp4: yes
#      routes:
#        - to: default
#          via: 192.168.1.1
      nameservers:
        addresses:
          - 1.1.1.1
          - 1.0.0.1
        search: []
      parameters:
        stp: true
        forward-delay: 4
      link-local: [ ipv6 ]
