# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    enp6s0:
      dhcp4: yes
#      addresses:
#      - 192.168.20.20/24
      nameservers:
        addresses:
        - 1.1.1.1
        - 1.0.0.1
        search: []
      routes:
      - to: default
        via: 192.168.20.1
      link-local: [ ipv6 ]
